# Generated by Django 5.1.2 on 2024-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dolist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="text",
        ),
        migrations.AddField(
            model_name="todolist",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="todolist",
            name="title",
            field=models.CharField(default="Untitled Task", max_length=100),
        ),
    ]
