# Generated by Django 5.1.2 on 2024-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dolist", "0003_todolist_completed_alter_todolist_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="description",
        ),
        migrations.AlterField(
            model_name="todolist",
            name="title",
            field=models.CharField(max_length=45),
        ),
    ]
